--JOB INFO 테이블 생성
CREATE TABLE JOB_INFO(
    JOb_ID      VARCHAR(10),    --직업 아이디
    MIN_SALARY  NUMBER,         --최저급여
    MAX_SALARY  NUMBER          --최고급여
);

INSERT INTO JOB_INFO VALUES('AD_PRES',20000,40000);
INSERT INTO JOB_INFO VALUES('AD_VP',15000,30000);
INSERT INTO JOB_INFO VALUES('AD_ASST',3000,4300);
INSERT INTO JOB_INFO VALUES('FI_MGR',8000,14000);
INSERT INTO JOB_INFO VALUES('FI_ACCOUNT',4000,9000);
INSERT INTO JOB_INFO VALUES('AC_MGR',8000,16000);
INSERT INTO JOB_INFO VALUES('AC_ACCOUNT',4000,9000);

COMMIT;

SELECT * FROM JOB_INFO;

--최저급여, 최고급여의 평균

SELECT ROUND(avg(MIN_SALARY),-2) AS 최저급여평균,
      ROUND(avg(MAX_SALARY),-2) AS 최고급여평균     
FROM JOB_INFO;

--최저 급여가 5000 달러 이상인 직업 아이디를 검색하시오\
/*실행 순서
1. FROM  ( 어떤 테이블이냐) 
2. WHERE
3. SELECT (칼럼 읽기)
4. ORDER ( 정렬)
*/
SELECT JOB_ID , MIN_SALARY MIN_SAL
FROM JOB_INFO
WHERE MIN_SALARY >= 5000;

-- 최저 급여가 5000 달러 이상인 정보를 검색한 뷰 생성
CREATE VIEW V_JOB_INFO
AS SELECT *
   FROM JOB_INFO
   WHERE MIN_SALARY >= 5000;
   
SELECT * FROM V_JOB_INFO;

--최고급여와 최저급여의 차가 10000달러 이상인 직업의 수를 구하시오
SELECT JOB_ID
FROM V_JOB_INFO
WHERE MAX_SALARY - MIN_SALARY >= 10000;

--직업 아이디의 이름이 FI로 시작하는 자료를 검색하시오
SELECT *
FROM  V_JOB_INFO
WHERE JOB_ID LIKE 'FI%';

--MAX_SALARY가 가장 높은 직업 아이디를 검색
SELECT *
       FROM V_JOB_INFO
WHERE MAX_SALARY = (SELECT MAX(MAX_SALARY) FROM V_JOB_INFO);



